import { Routes } from '@angular/router';

export const PAGES_ROUTES: Routes = [
  { path: '', redirectTo: 'ai-chat-with-suggestions', pathMatch: 'full' },
  { path: 'ai-chat-with-suggestions', loadComponent: () => import('./ai-chat-with-suggestions.component').then(m => m.AiChatWithSuggestionsComponent) },
  { path: 'ai-exam-generator-1', loadComponent: () => import('./ai-exam-generator-1.component').then(m => m.AiExamGenerator1Component) },
  { path: 'ai-exam-generator-2', loadComponent: () => import('./ai-exam-generator-2.component').then(m => m.AiExamGenerator2Component) },
  { path: 'ai-exam-generator-3', loadComponent: () => import('./ai-exam-generator-3.component').then(m => m.AiExamGenerator3Component) },
  { path: 'ai-exam-generator-4', loadComponent: () => import('./ai-exam-generator-4.component').then(m => m.AiExamGenerator4Component) },
  { path: 'ai-exam-generator-5', loadComponent: () => import('./ai-exam-generator-5.component').then(m => m.AiExamGenerator5Component) },
  { path: 'ai-exam-generator-6', loadComponent: () => import('./ai-exam-generator-6.component').then(m => m.AiExamGenerator6Component) },
  { path: 'ai-study-assistant-chat', loadComponent: () => import('./ai-study-assistant-chat.component').then(m => m.AiStudyAssistantChatComponent) },
  { path: 'app-loader-screen', loadComponent: () => import('./app-loader-screen.component').then(m => m.AppLoaderScreenComponent) },
  { path: 'app-snack-alerts-ui', loadComponent: () => import('./app-snack-alerts-ui.component').then(m => m.AppSnackAlertsUiComponent) },
  { path: 'competitive-challenge-hub-1', loadComponent: () => import('./competitive-challenge-hub-1.component').then(m => m.CompetitiveChallengeHub1Component) },
  { path: 'competitive-challenge-hub-2', loadComponent: () => import('./competitive-challenge-hub-2.component').then(m => m.CompetitiveChallengeHub2Component) },
  { path: 'competitive-challenge-hub-3', loadComponent: () => import('./competitive-challenge-hub-3.component').then(m => m.CompetitiveChallengeHub3Component) },
  { path: 'competitive-challenge-hub-4', loadComponent: () => import('./competitive-challenge-hub-4.component').then(m => m.CompetitiveChallengeHub4Component) },
  { path: 'competitive-challenge-hub-5', loadComponent: () => import('./competitive-challenge-hub-5.component').then(m => m.CompetitiveChallengeHub5Component) },
  { path: 'competitive-challenge-hub-6', loadComponent: () => import('./competitive-challenge-hub-6.component').then(m => m.CompetitiveChallengeHub6Component) },
  { path: 'competitive-challenge-hub-7', loadComponent: () => import('./competitive-challenge-hub-7.component').then(m => m.CompetitiveChallengeHub7Component) },
  { path: 'exam-catalog-1', loadComponent: () => import('./exam-catalog-1.component').then(m => m.ExamCatalog1Component) },
  { path: 'exam-catalog-2', loadComponent: () => import('./exam-catalog-2.component').then(m => m.ExamCatalog2Component) },
  { path: 'exam-catalog-3', loadComponent: () => import('./exam-catalog-3.component').then(m => m.ExamCatalog3Component) },
  { path: 'exam-history-1', loadComponent: () => import('./exam-history-1.component').then(m => m.ExamHistory1Component) },
  { path: 'exam-history-2', loadComponent: () => import('./exam-history-2.component').then(m => m.ExamHistory2Component) },
  { path: 'exam-history-3', loadComponent: () => import('./exam-history-3.component').then(m => m.ExamHistory3Component) },
  { path: 'exam-history-4', loadComponent: () => import('./exam-history-4.component').then(m => m.ExamHistory4Component) },
  { path: 'exam-history-5', loadComponent: () => import('./exam-history-5.component').then(m => m.ExamHistory5Component) },
  { path: 'exam-history-6', loadComponent: () => import('./exam-history-6.component').then(m => m.ExamHistory6Component) },
  { path: 'exam-history-7', loadComponent: () => import('./exam-history-7.component').then(m => m.ExamHistory7Component) },
  { path: 'exam-instructions-1', loadComponent: () => import('./exam-instructions-1.component').then(m => m.ExamInstructions1Component) },
  { path: 'exam-instructions-2', loadComponent: () => import('./exam-instructions-2.component').then(m => m.ExamInstructions2Component) },
  { path: 'exam-marksheet-pdf-ui', loadComponent: () => import('./exam-marksheet-pdf-ui.component').then(m => m.ExamMarksheetPdfUiComponent) },
  { path: 'leaderboards', loadComponent: () => import('./leaderboards.component').then(m => m.LeaderboardsComponent) },
  { path: 'live-challenge-scoreboard-1', loadComponent: () => import('./live-challenge-scoreboard-1.component').then(m => m.LiveChallengeScoreboard1Component) },
  { path: 'live-challenge-scoreboard-2', loadComponent: () => import('./live-challenge-scoreboard-2.component').then(m => m.LiveChallengeScoreboard2Component) },
  { path: 'live-challenge-scoreboard-3', loadComponent: () => import('./live-challenge-scoreboard-3.component').then(m => m.LiveChallengeScoreboard3Component) },
  { path: 'live-examination-1', loadComponent: () => import('./live-examination-1.component').then(m => m.LiveExamination1Component) },
  { path: 'live-examination-2', loadComponent: () => import('./live-examination-2.component').then(m => m.LiveExamination2Component) },
  { path: 'live-examination-3', loadComponent: () => import('./live-examination-3.component').then(m => m.LiveExamination3Component) },
  { path: 'live-examination-4', loadComponent: () => import('./live-examination-4.component').then(m => m.LiveExamination4Component) },
  { path: 'modern-login-screen-with-socials', loadComponent: () => import('./modern-login-screen-with-socials.component').then(m => m.ModernLoginScreenWithSocialsComponent) },
  { path: 'open-class-challenge', loadComponent: () => import('./open-class-challenge.component').then(m => m.OpenClassChallengeComponent) },
  { path: 'otp-email-template', loadComponent: () => import('./otp-email-template.component').then(m => m.OtpEmailTemplateComponent) },
  { path: 'otp-verification-screen', loadComponent: () => import('./otp-verification-screen.component').then(m => m.OtpVerificationScreenComponent) },
  { path: 'partner-institution-profile-1', loadComponent: () => import('./partner-institution-profile-1.component').then(m => m.PartnerInstitutionProfile1Component) },
  { path: 'partner-institution-profile-2', loadComponent: () => import('./partner-institution-profile-2.component').then(m => m.PartnerInstitutionProfile2Component) },
  { path: 'partner-institution-profile-3', loadComponent: () => import('./partner-institution-profile-3.component').then(m => m.PartnerInstitutionProfile3Component) },
  { path: 'privacy-policy', loadComponent: () => import('./privacy-policy.component').then(m => m.PrivacyPolicyComponent) },
  { path: 'profile-and-settings', loadComponent: () => import('./profile-and-settings.component').then(m => m.ProfileAndSettingsComponent) },
  { path: 're-connect-connection-screen', loadComponent: () => import('./re-connect-connection-screen.component').then(m => m.ReConnectConnectionScreenComponent) },
  { path: 'reset-password-screen', loadComponent: () => import('./reset-password-screen.component').then(m => m.ResetPasswordScreenComponent) },
  { path: 'review-success-celebration-screen', loadComponent: () => import('./review-success-celebration-screen.component').then(m => m.ReviewSuccessCelebrationScreenComponent) },
  { path: 'social-login-loading-state-1', loadComponent: () => import('./social-login-loading-state-1.component').then(m => m.SocialLoginLoadingState1Component) },
  { path: 'social-login-loading-state-2', loadComponent: () => import('./social-login-loading-state-2.component').then(m => m.SocialLoginLoadingState2Component) },
  { path: 'social-login-loading-state-3', loadComponent: () => import('./social-login-loading-state-3.component').then(m => m.SocialLoginLoadingState3Component) },
  { path: 'student-dashboard-1', loadComponent: () => import('./student-dashboard-1.component').then(m => m.StudentDashboard1Component) },
  { path: 'student-dashboard-2', loadComponent: () => import('./student-dashboard-2.component').then(m => m.StudentDashboard2Component) },
  { path: 'submit-exam-review-form', loadComponent: () => import('./submit-exam-review-form.component').then(m => m.SubmitExamReviewFormComponent) },
  { path: 'technical-issue-screen', loadComponent: () => import('./technical-issue-screen.component').then(m => m.TechnicalIssueScreenComponent) },
  { path: 'terms-of-service', loadComponent: () => import('./terms-of-service.component').then(m => m.TermsOfServiceComponent) },
  { path: 'testimonial-slider-landing-page', loadComponent: () => import('./testimonial-slider-landing-page.component').then(m => m.TestimonialSliderLandingPageComponent) },
  { path: '**', redirectTo: 'ai-chat-with-suggestions' },
];
